export const CATEGORY_COLORS = [
  '#667eea',
  '#764ba2',
  '#f093fb',
  '#f5576c',
  '#11998e',
  '#38ef7d',
  '#4facfe',
  '#00f2fe',
  '#fa709a',
  '#fee140',
  '#feca57',
  '#ff9ff3',
  '#ee5a6f',
  '#c471ed',
  '#12c2e9',
  '#f64f59',
  '#95a5a6',
  '#34495e',
] as const;

export const CATEGORY_ICONS = [
  'briefcase',
  'home',
  'fitness',
  'cart',
  'book',
  'heart',
  'star',
  'cafe',
  'airplane',
  'car',
  'bicycle',
  'game-controller',
  'musical-notes',
  'camera',
  'gift',
  'trophy',
  'school',
  'medkit',
  'restaurant',
  'pizza',
  'basketball',
  'football',
  'barbell',
  'bed',
] as const;

export const DEFAULT_CATEGORY_COLOR = CATEGORY_COLORS[0];
export const DEFAULT_CATEGORY_ICON = CATEGORY_ICONS[0];
